<a href="https://colab.research.google.com/github/HromovAndrey/-_2_-_-_-/blob/laba/Laba2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

In [13]:
b = np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [14]:
print(b.shape)

(2, 2)


In [16]:
c = np.ones((2,4))
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
p = np.random.random((3,2))
print(p)

[[0.83602542 0.10301411]
 [0.16993532 0.22796589]
 [0.15140417 0.71521318]]


In [19]:
v = np.full((2,2),7)
print(v)

[[7 7]
 [7 7]]


In [20]:
z = np.eye(2)
print(z)

[[1. 0.]
 [0. 1.]]


In [21]:
x = np.arange(10,50,5)
print(x)

[10 15 20 25 30 35 40 45]


In [22]:
m = np.arange(1,25,3)
print(m)

[ 1  4  7 10 13 16 19 22]


In [25]:
a = np.linspace(0., 6., num=8)
print(a)

[0.         0.85714286 1.71428571 2.57142857 3.42857143 4.28571429
 5.14285714 6.        ]


In [26]:
s = np.array([3,4,5])
d = np.array([6,7,8])
print(f"{s=}\n")
print(f"{d=}\n")
np.vstack((s,d))

s=array([3, 4, 5])

d=array([6, 7, 8])



array([[3, 4, 5],
       [6, 7, 8]])

In [28]:
s = np.array([[3], [5], [8]])
d = np.array([[2], [4], [6]])

print(f"{s=}\n")
print(f"{d=}\n")
np.hstack((s,d))

s=array([[3],
       [5],
       [8]])

d=array([[2],
       [4],
       [6]])



array([[3, 2],
       [5, 4],
       [8, 6]])

In [37]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print(a)
print(a[0:2,1:3])
print(a[0:3, 0])
d = a[0:2, 1:3]
print(d)
row_r1 = a[1, :]
row_r2 = a[1:2, :]
row_r3 = a[[1], :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
[1 5 9]
[[2 3]
 [6 7]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [38]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
row_r1 = a[1, :]
row_r2 = a[1:2, :]
row_r3 = a[[1], :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [39]:
row_r1 = a[1, :]
row_r2 = a[1:2, :]
row_r3 = a[[1], :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [41]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1)
print(col_r1, col_r1.shape)
print(col_r2)
print(col_r2, col_r2.shape)

[ 2  6 10]
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]]
[[ 2]
 [ 6]
 [10]] (3, 1)


In [46]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
q = np.array([0, 2, 0])
a[range(4), q] +- 10
print(a)
print(a[range(3), q])

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (4,) (3,) 

In [48]:
a = np.array([[1,2], [3,4], [5,7]])
bool_idx = (a > 2)
                   # знайти елементи якийбольше2
                   # поверне масив з True/False такого ж розмыру як а
                   # де кожен елемент bool_ idx каже
                   # чи виконуэться умова для выдповыдного елемента
print(bool_idx)
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 7]


In [49]:
a = np.array([1, 8, 9, -3, 2, 4, 7, 9])
print(np.argmax(a))
print(np.argmin(a))
print(np.argsort(a))
print(np.argsort(a)[::-1])
print(np.where(a > 5)[0])

2
3
[3 0 4 5 6 1 2 7]
[7 2 1 6 5 4 0 3]
[1 2 6 7]
