<a href="https://colab.research.google.com/github/HromovAndrey/-_2_-_-_-/blob/main/%D0%94%D0%97_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [1]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [3]:
a = np.arange(30, 71, 2)
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію

In [4]:
b = np.linspace(0, 1, 11, endpoint=False)[1:]
print(b)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [5]:
a = np.linspace(0., 1., num=10)
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [8]:
matrix = np.array([[1, 2], [3, 4]])
n = matrix.shape[0]
new_matrix = np.zeros((n + 2, n + 2), dtype=matrix.dtype)
new_matrix[1:n+1, 1:n+1] = matrix
print(new_matrix)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [9]:
matrix = np.array([[1, 2], [3, 4]])
n = matrix.shape[0]
new_matrix = np.zeros((n + 2, n + 2), dtype=matrix.dtype)
new_matrix[1:n+1, 1:n+1] = matrix
print("Новая матрица до изменения типа данных:")
print(new_matrix)
print("Тип данных до изменения:", new_matrix.dtype)
new_matrix = new_matrix.astype(float)
print("\nНовая матрица после изменения типа данных:")
print(new_matrix)
print("Тип данных после изменения:", new_matrix.dtype)



Новая матрица до изменения типа данных:
[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]
Тип данных до изменения: int64

Новая матрица после изменения типа данных:
[[0. 0. 0. 0.]
 [0. 1. 2. 0.]
 [0. 3. 4. 0.]
 [0. 0. 0. 0.]]
Тип данных после изменения: float64


#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [14]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5
q = x.copy()
q[q == var] = -1
q[q > var] = -1
q[q < var] = -1
print(x)
print(q)


[1 5 3 8 6 5 7 4]
[-1 -1 -1 -1 -1 -1 -1 -1]


#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [15]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])
X[np.isnan(X)] = -1
print(X)

[[ 1.  2. -1.  4.]
 [ 5. -1. -1.  4.]
 [-1. 10. 11. -1.]]


#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [21]:
f = np.random.rand(4,6)
z = np.reshape(f,(3,8))
print(f)
print(z)

[[0.10508539 0.66861217 0.29618294 0.96101143 0.98553222 0.25137443]
 [0.8637326  0.08777198 0.19295569 0.48966721 0.68480269 0.37932392]
 [0.20345207 0.52200135 0.91886122 0.2286542  0.61409397 0.92137504]
 [0.04150235 0.42595474 0.31598777 0.50203192 0.10169939 0.76676518]]
[[0.10508539 0.66861217 0.29618294 0.96101143 0.98553222 0.25137443
  0.8637326  0.08777198]
 [0.19295569 0.48966721 0.68480269 0.37932392 0.20345207 0.52200135
  0.91886122 0.2286542 ]
 [0.61409397 0.92137504 0.04150235 0.42595474 0.31598777 0.50203192
  0.10169939 0.76676518]]


#Завдання 9
Створіть матрицю з одиниць розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [24]:
c = np.ones((3,4))
v = np.mean(c, axis=0)
print(c)
print(v)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1. 1. 1. 1.]


#Завдання 10
Створіть випадкову матрицю розміром 5х6. Округліть значення до одного знаку після коми(np.round). Розмістіть стовпчики так, щоб значення в першому рядку були відсортовані за зростанням

In [25]:
n = np.random.rand(5,6)
m = np.round(n, 1)
sorted_indices = np.argsort(m[0])
sorted_matrix = m[:,sorted_indices]
print(n)
print(m)
print(sorted_matrix)

[[0.22038048 0.17790232 0.50559774 0.4586858  0.63325713 0.24884418]
 [0.34026569 0.41843096 0.26041404 0.80493678 0.03780223 0.12030495]
 [0.09031404 0.31598893 0.39301717 0.87498291 0.77760522 0.40462098]
 [0.24730407 0.8817153  0.62872401 0.29143053 0.22905122 0.07255703]
 [0.01736395 0.88188135 0.58394523 0.99223547 0.97578687 0.86253128]]
[[0.2 0.2 0.5 0.5 0.6 0.2]
 [0.3 0.4 0.3 0.8 0.  0.1]
 [0.1 0.3 0.4 0.9 0.8 0.4]
 [0.2 0.9 0.6 0.3 0.2 0.1]
 [0.  0.9 0.6 1.  1.  0.9]]
[[0.2 0.2 0.2 0.5 0.5 0.6]
 [0.3 0.4 0.1 0.3 0.8 0. ]
 [0.1 0.3 0.4 0.4 0.9 0.8]
 [0.2 0.9 0.1 0.6 0.3 0.2]
 [0.  0.9 0.9 0.6 1.  1. ]]


#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [26]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])
g = np.logical_and(X >= 3, X <= 6)
result = X[g]
print(result)

[3 4 5 6 6 5 4 3]


#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом цього стовпчика.

Після цього всі значення мають бути в межах [0, 1]

In [27]:
h = np.random.rand(5,6)

min_values = np.min(matrix, axis=0)
max_values = np.max(matrix, axis=0)
normalized_matrix = (matrix - min_values) / (max_values - min_values)
print(h)
print(normalized_matrix)

[[0.50621785 0.17288196 0.06310469 0.04748794 0.08106937 0.32923406]
 [0.05064957 0.12215419 0.01590817 0.5654449  0.33292589 0.12167243]
 [0.05735832 0.26684873 0.01352698 0.97055612 0.64076378 0.12274817]
 [0.22729029 0.31514675 0.54135414 0.12462277 0.10580301 0.45896485]
 [0.27268291 0.32123763 0.61792867 0.64348669 0.3770867  0.83559696]]
[[0. 0.]
 [1. 1.]]
